packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@expo/cli@56.1.15'
  - '@expo/log-box@56.0.13'
  - '@expo/metro-config@56.0.14'
  - '@turbo/darwin-64@2.9.18'
  - '@turbo/darwin-arm64@2.9.18'
  - '@turbo/linux-64@2.9.18'
  - '@turbo/linux-arm64@2.9.18'
  - '@turbo/windows-64@2.9.18'
  - '@turbo/windows-arm64@2.9.18'
  - '@types/node@25.9.3'
  - babel-preset-expo@56.0.15
  - eslint-plugin-turbo@2.9.18
  - expo-asset@56.0.17
  - expo-constants@56.0.18
  - expo-file-system@56.0.8
  - expo-font@56.0.6
  - expo-modules-core@56.0.16
  - expo-modules-jsi@56.0.9
  - expo@56.0.11
  - turbo@2.9.18
